## 1. One word at a time

In [1]:
import pandas as pd

text = ['cat', 'dog', 'fish', 'bird', 'cat', 'dog']

data = pd.get_dummies(text)

print(data)
print('-'*30)
print(data.keys())

    bird    cat    dog   fish
0  False   True  False  False
1  False  False   True  False
2  False  False  False   True
3   True  False  False  False
4  False   True  False  False
5  False  False   True  False
------------------------------
Index(['bird', 'cat', 'dog', 'fish'], dtype='object')


In [2]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

text = ['i love dogs', 'i hate cats', 'i like turtles', 'i love the dogs']

text = np.reshape(text, (-1, 1))


encoder = OneHotEncoder()
encoder.fit(text)

one_hot = encoder.transform(text)

print(one_hot.toarray())
print([i[3:]for i in encoder.get_feature_names()])

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


AttributeError: 'OneHotEncoder' object has no attribute 'get_feature_names'

In [3]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

text = ['i love dogs', 'i hate cats', 'i like turtles', 'i love the dogs']
text = np.reshape(text, (-1, 1))

encoder = OneHotEncoder()
encoder.fit(text)

one_hot = encoder.transform(text)

print(one_hot.toarray())
print([i for i in encoder.get_feature_names_out()])


[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
['x0_i hate cats', 'x0_i like turtles', 'x0_i love dogs', 'x0_i love the dogs']


In [4]:
pd.DataFrame(one_hot.toarray(), columns = [i[3:]for i in encoder.get_feature_names()])

AttributeError: 'OneHotEncoder' object has no attribute 'get_feature_names'

In [5]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

text = ['i love dogs', 'i hate cats', 'i like turtles', 'i love the dogs']
text = np.reshape(text, (-1, 1))

encoder = OneHotEncoder()
encoder.fit(text)

one_hot = encoder.transform(text)

# Use get_feature_names_out instead of get_feature_names
df = pd.DataFrame(one_hot.toarray(), columns=encoder.get_feature_names_out())
print(df)


   x0_i hate cats  x0_i like turtles  x0_i love dogs  x0_i love the dogs
0             0.0                0.0             1.0                 0.0
1             1.0                0.0             0.0                 0.0
2             0.0                1.0             0.0                 0.0
3             0.0                0.0             0.0                 1.0
